# Generated by Django 4.1.4 on 2023-03-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_scope_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scope',
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Тематика'),
        ),
    ]
