# Generated by Django 4.1.4 on 2023-03-11 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_tag_articles_alter_scope_article_alter_scope_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
