# Generated by Django 4.1.4 on 2023-03-11 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_scope_is_main_alter_scope_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'ordering': ['-is_main', '-tag'], 'verbose_name': 'тег', 'verbose_name_plural': 'теги'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Тематики'},
        ),
    ]
